#!/bin/bash

ROOT=`pwd`
SRC=$ROOT/
LIB=$ROOT/external/lib
BIN=$ROOT/bin

mkdir $LIB
mkdir $BIN

CXXFLAGS=-g

source mk

INCLUDE="-I$ROOT/external/include/zero -I$ROOT/vndc/include"

newtd
	mkmcc		external/src/zero
	mkar 		libZero
deltd

LDFLAGS=-lZero

newtd
	mkmcc vndc/src
	mkld		vndc
deltd
